### ISSUE TITLE
Creating 2k Posts crashes lenie

### ISSUE THREAD

**Issue by Rehwanne** [lamarpavel/lenie#10]
I created 1k posts which worked, after that i created 1k more and lenie crashed:

remote: luajit: /usr/local/bin/lenie.lua:178: attempt to index a nil value
remote: stack traceback:
remote: 	/usr/local/bin/lenie.lua:178: in function 'gen_html'
remote: 	/usr/local/bin/lenie.lua:287: in function 'generate'
remote: 	/usr/local/bin/lenie.lua:475: in function 'main'
remote: 	/usr/local/bin/lenie.lua:482: in main chunk
remote: 	[C]: at 0x00405360

**Comment by lamarpavel** [comment]
Seems to have been an issue with a dangling file descriptor. Should be fixed in in https://github.com/lamarpavel/lenie/commit/b760807a24d71ab00288bbf1e9f239d10c052881
