### ISSUE TITLE
feature request: add a footer.md

### ISSUE THREAD

**Issue by Rehwanne** [lamarpavel/lenie#11]
It would be desirable to be able to have a footer and not only the preamble.md as a header

**Comment by lamarpavel** [comment]
Added with https://github.com/lamarpavel/lenie/commit/af702eb60aa2b7cfb328e47e36a62f66e42e9bfd

Just as with preamble.md *lenie* is now looking for a footer.md in the working directory. If she finds it, the HTML code generated from it will be added at the bottom of every page.
