### ISSUE TITLE
Let lenie sleep after generation of N posts

### ISSUE THREAD

**Issue by lamarpavel** [lamarpavel/lenie#20]
In the case of a blog hoster, serving lots of users, a possible attack vector for a malicious user would be to repeatedly commit thousands of posts with random data, eating up 100% CPU time on one core. Limiting the number of new posts is not an acceptable solution as that would interfere with the legitimate scenario of migrating large blogs from one hoster to another or re-generating an entire blog due to changed colors scheme etc.

To render such an attack mostly harmless *lenie* could simply sleep for *M* milliseconds after generating *N* posts, where *N* and *M* are values defined by the system administrator.
Regular usage of *lenie* - generating only a few posts once in a while - takes less than a second even on low-end CPUs. If intense operations (be that malicious attacks or legitimate scenarios) are put to sleep in sensible intervals, they would have a significantly smaller impact on execution of regular calls to *lenie*.

This behaviour should make *lenie* less attractive for attackers than other vectors without limiting genuine usage.

**Comment by lamarpavel** [comment]
As of https://github.com/lamarpavel/lenie/commit/5d357dccf3be2f3954f06ce59f5c75e4085004d0 sleeping is implemented and working, however it is not yet useful in the above described scenario as the parameters for sleep_interval and sleep_duration can be modified via rc.lua.

To solve this *lenie* needs to read two distinct config files, one of which can not be modified by the user but only by the admin.

**Comment by JAEGER2K** [comment]
> To solve this lenie needs to read two distinct config files, one of which can not be modified by the user but only by the admin.
They don't need to be distinct. How about the admin config file gets red before the user config file, thus replacing every "evil" value which shouldn't be set by the user

**Comment by lamarpavel** [comment]
>They don't need to be distinct. How about the admin config file gets red before the user config file, thus replacing every "evil" value which shouldn't be set by the user

The admin config file should be somewhere the users can't modify it, like /etc/lenierc.lua. That's what I meant by "distinct". Though generally it would get pretty complicated for them to overwrite each other, because for some settings you want to give the admin the priority and for others you want the user to have the final decision.

Performance related settings should only be set by the system admin. For blog appearance on the other hand might be handy to provide a default via the admin setting that can then be overwritten by the users own color scheme or CSS.
