### ISSUE TITLE
[RFC] Distinct runtime configurations

### ISSUE THREAD

**Issue by lamarpavel** [lamarpavel/lenie#21]
Currently there is only *rc.lua*, located in the blogs working directory. That means all possible config can be modified by the user. In the scenario of a blog hoster with one sys admin and several users this is a potential problem. My current position is that there should be three runtime configs for *lenie* to look for:

- **Blog-specific**: The blogs working directory, where the current rc.lua resides
- **Global**: In /etc, where only the sys admin has write permission
- **User**: In the users $HOME/.config - where the user can set defaults for all their blogs

All of them should be optional but they are read in the following order, overwriting previous config:

1. User
2. Blog-specific
3. Global

Missing config files are skipped and if a setting is not configured at all, the hardcoded default will be used, just as it is now.

The remaining question is: *Should all of these files be allowed to set all possible settings*? It doesn't make sense for the user to set performance-related options, but to add restrictions is non-trivial in the current implementation and might mean a lot of work.

**Comment by JAEGER2K** [comment]
> Should all of these files be allowed to set all possible settings?

In my opinion: yes, but ...
You have a implicit priority with this management of configuration, and different fallbacks:

1. configuration by the sys admin (highest prio)
2. configuration per system user
3. configuration per blog
4. hard coded defaults (lowest)

and IMHO 1. and 2. or 2. and 3. don't differ, so you can either merge one of them.
Instead I would recommend to read 3 config files:

1. global forced configuration by sys admin
2. configuration per blog
3. global recommended (=default) configuration by sys-admin

And a implementation would look like this:

	load(/etc/lenie/defaults.lua)
	load(rc.lua) // overwrites defaults
	load(/etc/lenie/forced.lua) // overwrites blog custom

thus giving the sys admin the freedom to declare any configuration as forced or recommended

**Comment by lamarpavel** [comment]
Sounds good to me, I'll go read a bit about file system hierarchy to make sure /etc/lenie would be the apropriate place for this before I implement it.

**Comment by lamarpavel** [comment]
As of https://github.com/lamarpavel/lenie/commit/7ef62b4cccd1e14589f5dc2fa8182cd185b00db9 support for multiple config files is implemented. As described in the README.md these files are:

1. /etc/lenie/defaults.lua
2. rc.lua
3. /etc/lenie/enforced.lua
