### ISSUE TITLE
Function to sanitize path strings

### ISSUE THREAD

**Issue by lamarpavel** [lamarpavel/lenie#22]
Currently a string like /home/user/blog/.git/./../src/rev is passed by the git hook to *lenie* and is stored that way. This works because the shell resolves it for use when passed to a command, but in debug prints it's ugly and harder to read. A function **sanitize_path(s)** would be useful.

**Comment by JAEGER2K** [comment]
http://linux.die.net/man/3/realpath

**Comment by lamarpavel** [comment]
Wow, so that not just solves that problem, it could also replace most - if not all - of *lenies* patch checking code. I'll work on that immediately.

**Comment by lamarpavel** [comment]
Implemented in https://github.com/lamarpavel/lenie/commit/086e03f458db40b901c1ab679ada252e95d565d1

Sadly realpath(3) in stdlib.h does not have the same feature set as realpath(1), thus I only use it to enhance the capability of abspath() to also solve symlinks, ./ and ../, hence that function is now called sanitize_path().
