### ISSUE TITLE
relative paths on init - assertion error

### ISSUE THREAD

**Issue by JAEGER2K** [lamarpavel/lenie#6]
2 folders:
blog -- /home/jgr/lenie_test 
html -- /home/jgr/lenie_www

	$ pwd
	/home/jgr/lenie_test

init with relative paths:

	$ lenie init test ../lenie_www/
	stack traceback:
		[C]: in function 'assert'
		lenie:60: in function 'access'
		lenie:322: in function 'init'
		lenie:458: in function 'main'
		lenie:470: in main chunk
		[C]: at 0x00405360

init with absolute paths:

	$ lenie init /home/jgr/lenie_test/test /home/jgr/lenie_www/                           
	Initialized empty shared Git repository in /home/jgr/lenie_test/test/git/

**Comment by lamarpavel** [comment]
Right, I consider this a bug for now. *lenie* should either handle relative paths properly or it needs to be clear that she doesn't.

**Comment by lamarpavel** [comment]
Fixed in https://github.com/lamarpavel/lenie/commit/7ea3c84c9a2bcc7813178b09f042e35507fdabb1
