### ISSUE TITLE
Replace markdown.pl

### ISSUE THREAD

**Issue by lamarpavel** [lamarpavel/lenie#9]
The goal of this would be to have a slightly extended feature set in the markdown dialect. Something that allows insertion of images and so on.

A hot candidate is [markdown.lua](http://www.frykholm.se/files/markdown.lua), but I haven't actually investigated its feature set yet.

Another one would be an implementation of the GitHub Markdown dialect, I think the official implementation is in Python and under a FOSS license. This one is interesting because it's obviously well tested.

**Comment by JAEGER2K** [comment]
see https://github.com/JAEGER2K/lenie/commit/be8b387938c40c5bd07faa0d6d6059d43ab4480c
works for me but further testing required. I assume lua-markdown is properly installed.

**Comment by JAEGER2K** [comment]
a lua binding to a c markdown processor: https://github.com/asb/lua-discount/

**Comment by lamarpavel** [comment]
Performance is pretty important as this is at the heart of the work being done. A pure Lua implementation could prove to be very fast as it could be included in *lenie* via "local md = require(...)" and thus share memory with *lenie* directly.

A binding to a C lib could also be very fast as memory would be shared via stack in the same process and potentially it could be possible to have multiple threads running.

Either solution would probably be faster than markdown.pl.

Aside from performance it would be nice to have some additional features that are not included in [plain markdown](https://en.wikipedia.org/wiki/Markdown#Example) such as embedding images. For that the markdown parser would need to understand one of the extended markdown dialects.

Obviously a permissive FOSS licence is required. And those are all the requirements I can think of right now.

**Comment by JAEGER2K** [comment]
testing so far using [1]

```
README.md	1	0	0	0
syntax.md	1	0	0	0
README.md	10	1	0	0
syntax.md	10	2	3	0
README.md	100	6	4	0
syntax.md	100	13	34	0
README.md	1000	61	43	1
syntax.md	1000	128	345	1
README.md	10000	626	413	8
syntax.md	10000	1263	3478	16
```

README.md is lenie's readme
syntax.md is [2]


> Aside from performance it would be nice to have some additional features that are not included in [plain markdown](https://en.wikipedia.org/wiki/Markdown#Example) such as embedding images. For that the markdown parser would need to understand one of the extended markdown dialects.

embedding images is supported by all markdown compilers.
I concatinated the examples from [3] and fired up my script again. Only
the processing of multiline-code between ticks deviates on all compilers.



[1](https://gist.github.com/JAEGER2K/b6c17dc39222419ec323)
[2](http://daringfireball.net/projects/markdown/syntax.text)
[3](https://guides.github.com/features/mastering-markdown/#examples)

**Comment by JAEGER2K** [comment]
testing so far using https://gist.github.com/JAEGER2K/b6c17dc39222419ec323

```
file	    iter	md.pl	lua-md	lua-discount
README.md	1	    0	    0	    0
syntax.md	1	    0	    0	    0
README.md	10	    1	    0	    0
syntax.md	10	    2	    3	    0
README.md	100	    6	    4	    0
syntax.md	100	    13	    34	    0
README.md	1000	61	    43	    1
syntax.md	1000	128	    345	    1
README.md	10000	626	    413	    8
syntax.md	10000	1263	3478	16
```
time is in seconds

README.md is lenie's readme
syntax.md is http://daringfireball.net/projects/markdown/syntax.text


> Aside from performance it would be nice to have some additional features that are not included in [plain markdown](https://en.wikipedia.org/wiki/Markdown#Example) such as embedding images. For that the markdown parser would need to understand one of the extended markdown dialects.

embedding images is supported by all markdown compilers.
I concatinated the examples from [Mastering Markdown](https://guides.github.com/features/mastering-markdown/#examples) and fired up my script again. Only
the processing of multiline-code between ticks deviates on all compilers.

**Comment by lamarpavel** [comment]
The performance of the Lua bindings for discount looks very promising.

The way I implemented the calls to markdown.pl are tremendously naive and not good for the code hygene, if you are working on this consider replacing those io.popen calls with a call to a function that wraps around your markdown-to-html parsing.

**Comment by lamarpavel** [comment]
As of https://github.com/lamarpavel/lenie/commit/245414f16e5706d0f539f40c8693e4be6c9859f3 markdown.pl is replaced by [lua-discount](https://github.com/h0tw1r3/lua-discount).
